// Pure lookup over a precomputed manifest — NO `fs`, NO `image-size`, so this
// module is safe to import from bundled/SSR pages (Cloudflare edge has no
// filesystem). The manifest is generated by scripts/build-image-manifest.mjs,
// which runs before `astro build`.
import dims from '../data/image-dims.json';

/** Intrinsic pixel dimensions for a public image path like "/images/foo.webp".
 *  Returns { width, height } or null if the image isn't in the manifest. */
export function getImageDims(src) {
  return dims[src] ?? null;
}

/** Images to advertise in Recipe JSON-LD. Google recommends supplying 16:9,
 *  4:3 and 1:1 variants so it can pick the best fit per search surface.
 *  Falls back to the original if the generated crops aren't present. */
export function getSchemaImages(src) {
  const stem = src.replace(/\.webp$/, '');
  const variants = [];

  for (const ratio of ['16x9', '4x3', '1x1']) {
    const url = `${stem}-${ratio}.webp`;
    const d = getImageDims(url);
    if (d) variants.push({ url, ...d });
  }

  if (variants.length === 0) {
    const d = getImageDims(src);
    if (d) variants.push({ url: src, ...d });
  }

  return variants;
}
